id: 601931e9a07742528d02648c425dd91e
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN800
  title: སྤྱི་ལོ ༢༠༠༩་ལོར་དྷརྨ་སོགས་ཀྱིས་ཉར་ཚགས་བྱས་པའི་སྡེ་དགེའི་དམངས་ཁྲོད་ཀྱི་གནའ་དཔེ་བྲིས་མའི་གློག་རྡུལ་འདྲ་བཤུས།
  volumes:
    452ad68f660c4b2f9773b843d98a2a9d:
      image_group_id: I2KG229633
      title: ''
      base_file: v001.txt
  author: ''
